### ISSUE TITLE
T-Rex unmovable

### ISSUE THREAD

**Issue by jcdodson** [IvanGav/Crazy9x9JS#3]
I came here to play a good game of Jurassic Chess and saw that my favorite dinosaur cannot be moved. Sad.

**Comment by IvanGav** [comment]
T-Rex (Rex) moves diagonally and vertically up 2 squares, and as a knight up, but only if it has a path there, and diagonally 1 square down. It works on my end. Could you tell me more about the issue?

**Comment by IvanGav** [comment]
(Btw, how to play is hopefully coming in update 2)

**Comment by jcdodson** [comment]
Thank you, Issue resolved. I can now play my favorite dinsaur

**Comment by IvanGav** [comment]
Glad to hear that!
